version: 2

sources:
  - name: raw_london_energy  # Raw dataset name
    database: smart-meters-london # Your GCP Project ID
    tables:
      # External tables created via Kestra
      - name: daily_consumption_ext
      - name: hh_consumption_ext
      # Dimensions ingested via dlt
      - name: weather_daily_darksky
      - name: uk_bank_holidays
      - name: informations_households
