version: 2

models:
  - name: stg_daily_consumption
    description: "Staging Layer: Cleaned daily energy consumption data per London household."
    columns:
      - name: household_id
        description: "Unique household meter ID."
        tests:
          - not_null

      - name: consumption_date
        description: "Date when the consumption was recorded."
        tests:
          - not_null

      - name: energy_sum
        description: "Total energy consumption for the day (kWh)."
        tests:
          - not_null

  - name: stg_weather_daily
    description: "Staging Layer: Daily London weather data (DarkSky)."
    columns:
      - name: weather_date
        tests:
          - not_null
      - name: max_temp_celsius # Quality control check for temperature values
        tests:
          - not_null