# 📊 TRABAJO 2: REVISAR DBT
  dbt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-bigquery
        run: pip install dbt-bigquery==1.11.1

      - name: Create dummy dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          london_energy_dbt:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: oauth
                project: dummy-project
                dataset: dummy_dataset
          EOF

      - name: Check dbt syntax
        run: |
          cd london_energy_dbt
          
          # Creamos el perfil falso en la misma carpeta del proyecto
          cat <<EOF > profiles.yml
          london_energy_dbt:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: oauth
                project: dummy-project
                dataset: dummy_dataset
          EOF
          
          # Le decimos a dbt expresamente que busque el perfil en la carpeta actual (.)
          dbt deps --profiles-dir .
          dbt parse --profiles-dir .